version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  goapp:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - "./api:/go/src/github.com/wangppp/shuffle/api"
    ports:
      - "5000:4000"
    depends_on:
      - db
    links:
      - db
    environment:
    - VIRTUAL_HOST=adminpanel.epic-think.xyz
  db:
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  blog:
    build: ./blog
    links:
      - goapp
    ports:
      - "3999:3000"
    environment:
      - VIRTUAL_HOST=epic-think.xyz
    