export const CHANGE_IMAGE_LIST = "MEDIA/CHANGE_IMAGE_LIST";
export const CHANGE_PAGE = "MEDIA/CHANGE_PAGE";
export const CHANGE_PAGE_STATE = "MEDIA/CHANGE_PAGE_STATE";
export const CHANGE_COUNT_AND_LIST = "MEDIA/CHANGE_COUNT_AND_LIST";
export const CHANGE_SELECTED_IMG = "MEDIA/CHANGE_SELECTED_IMG";
